// Command modules
pub mod auth;
pub mod gmail;
pub mod ai;
pub mod database;
pub mod settings;
pub mod notification;
pub mod fs;
pub mod crm;
pub mod chatbot;
pub mod email_storage;
pub mod life_data;
pub mod web_search;