apiVersion: v1
kind: Service
metadata:
  name: genai-gateway-canary
  namespace: aiden
spec:
  type: ClusterIP
  selector:
    app: genai-gateway
    track: canary
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
