import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { durableStorage } from '@/lib/persistentStore';

/**
 * Per-contact memory.
 *
 * The relationship context notes ("what they're working on / what's pending") are
 * generated by the LLM but were thrown away after each render, so Aiden re-skimmed
 * every time instead of *remembering*. This store persists those notes keyed by
 * email so they survive sessions, show instantly on revisit, and can be fed into
 * reply drafting and meeting prep — the difference between an assistant who
 * remembers a person and one who re-reads their inbox each time.
 */
interface ContactNote {
  bullets: string[];
  updatedAt: string;
}

interface ContactMemoryState {
  notes: Record<string, ContactNote>;
  setNotes: (email: string | undefined, bullets: string[]) => void;
  getNotes: (email: string | undefined) => string[];
}

const norm = (raw?: string): string => {
  if (!raw) return '';
  const m = raw.match(/<([^>]+)>/);
  return (m ? m[1] : raw).trim().toLowerCase();
};

export const useContactMemoryStore = create<ContactMemoryState>()(
  persist(
    (set, get) => ({
      notes: {},
      setNotes: (email, bullets) => {
        const key = norm(email);
        if (!key || !bullets.length) return;
        set((state) => ({
          notes: {
            ...state.notes,
            [key]: { bullets: bullets.slice(0, 4), updatedAt: new Date().toISOString() },
          },
        }));
      },
      getNotes: (email) => get().notes[norm(email)]?.bullets ?? [],
    }),
    { name: 'aiden-contact-memory', storage: createJSONStorage(() => durableStorage) },
  ),
);
