apiVersion: v1
kind: Service
metadata:
  name: email-calendar
  namespace: aiden
spec:
  type: ClusterIP
  selector:
    app: email-calendar
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
